image: alpine:3.9.4
pipelines:
  branches:
    master:
      - step:
          name: Update BUS_API_SERVER_COMMIT config var in bus-api-terraform-backend
          script:
            - apk --no-cache add curl
            - curl -sSfX PATCH
              -d '{"BUS_API_SERVER_COMMIT":"'"$BITBUCKET_COMMIT"'"}'
              -H "Content-Type:application/json"
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"
              https://api.heroku.com/apps/bus-api-terraform-backend/config-vars