image: maven:3.6.1-jdk-11-slim
pipelines:
  branches:
    master:
      - step:
          name: Test project and update BUS_API_SERVER_COMMIT config var in bus-api-terraform-backend
          script:
            - mvn -e -B test
            - curl -sSfX PATCH
              -o /dev/null
              -d '{"BUS_API_SERVER_COMMIT":"'"$BITBUCKET_COMMIT"'"}'
              -H "Content-Type:application/json"
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"
              https://api.heroku.com/apps/bus-api-terraform-backend/config-vars