clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Deploy to Heroku
          deployment: production
          script:
            - curl -X PATCH https://api.heroku.com/apps/bus-api-terraform-backend/config-vars
              -d '{"BUS_API_SERVER_COMMIT":"'"$BITBUCKET_COMMIT"'"}'
              -H "Content-Type:application/json"
              -H "Authorization:Bearer $HEROKU_API_KEY"
              -H "Accept:application/vnd.heroku+json; version=3"