transportApiClient:
  url: ${TRANSPORT_API_CLIENT_URL:https://transportapi.com/v3/uk/}
  applicationId: ${TRANSPORT_API_CLIENT_APPLICATION_ID:defaultApplicationIdValue}
  applicationKey: ${TRANSPORT_API_CLIENT_APPLICATION_KEY:defaultApplicationKeyValue}

feign:
  hystrix:
    enabled: false
  client:
    config:
      transportApiClient:
        loggerLevel: full

debug: true

logging:
  level:
    io.github.robertograham.busapi.client.TransportApiClient: DEBUG

spring:
  jackson:
    default-property-inclusion: NON_NULL

server:
  servlet:
    context-path: /api
