version: 2.1
commands:
  setup-remote-docker:
    steps:
      - setup_remote_docker:
          version: 19.03.13

executors:
  docker:
    docker:
      - image: docker:19.03.13-git

jobs:
  build-docker-image:
    executor: docker
    steps:
      - checkout
      - setup-remote-docker
      - run: |
          docker build --target builder -t departure-api-builder .
          mkdir ~/test-results
          docker cp $(docker create departure-api-builder):/src/target/surefire-reports ~/test-results/spock
      - store_test_results:
          path: ~/test-results
  publish-docker-image:
    executor: docker
    environment:
      IMAGE_TAG: ghcr.io/robertograham/departure-api:$CIRCLE_SHA1
    steps:
      - checkout
      - setup-remote-docker
      - run: |
          docker login ghcr.io -u RobertoGraham -p $PERSONAL_ACCESS_TOKEN
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
  update-release-tag:
    docker:
      - image: curlimages/curl:7.66.0
    steps:
      - run: |
          curl -sSfX PATCH \
          -o /dev/null \
          -d '{"DEPARTURE_API_COMMIT_HASH":"'"$CIRCLE_SHA1"'"}' \
          -H "Content-Type:application/json" \
          -H "Authorization:Bearer $HEROKU_API_KEY" \
          -H "Accept:application/vnd.heroku+json; version=3" \
          https://api.heroku.com/apps/departure-infra-backend/config-vars

workflows:
  release:
    jobs:
      - build-docker-image:
          filters:
            branches:
              ignore: master
      - publish-docker-image:
          filters:
            branches:
              only: master
      - update-release-tag:
          requires:
            - publish-docker-image