version: 2.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          command: |
            docker login docker.pkg.github.com -u RobertoGraham -p $GITHUB_TOKEN
            IMAGE_TAG=docker.pkg.github.com/robertograham/departure-api/departure-api:$CIRCLE_SHA1
            docker build -t $IMAGE_TAG .
            docker push $IMAGE_TAG
            curl -sSfX PATCH \
            -o /dev/null \
            -d '{"DEPARTURE_API_COMMIT_HASH":"'"$CIRCLE_SHA1"'"}' \
            -H "Content-Type:application/json" \
            -H "Authorization:Bearer $HEROKU_API_KEY" \
            -H "Accept:application/vnd.heroku+json; version=3" \
            https://api.heroku.com/apps/departure-infra-backend/config-vars